id: P000112
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །མཁས་འཇུག་གི་སྡོམ་བྱང་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། འཇམ་མགོན་མི་ཕམ་རིན་པོ་ཆེ།
  layers:
  - book_title
  - author
  - chapter_title
  - quotation
  - sabche
  - yigchung
  id: LEK-PHI-006
web_metadata:
  title:
    en: A Summary of The Entrance to the Way of the Wise
    bo: མཁས་འཇུག་གི་སྡོམ་བྱང་བཞུགས་སོ།།
  collection:
    en: Lekshey Ling Philosophy Series–  Book 6
    bo: ལེགས་བཤད་གླིང་རིགས་པའི་གཞུང་ལུགས།–  དེབ། ༦
  author:
    en: Jamgon Mipham Gyatso
    bo: འཇམ་མགོན་མི་ཕམ་རྒྱ་མཚོ།
  pusblisher:
    en: Lekshey Ling Publications
    bo: ཀརྨ་ལེགས་བཤད་གླིང།
  sku: LEK-PHI-006
  category:
    en: Abhidharma
    bo: ཆོས་མངོན་པ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: LEK-PHI-006.epub
  description:
    en: ༄༅། །འདིར་ཤེས་བྱའི་གནས་མ་ནོར་བར་གཏན་ལ་འབེབས་པའི་ཤེས་རབ་ཐོབ་པར་འདོད་པས་མདོ་དང་བསྟན་བཅོས་ཆེན་པོ་རྣམས་ལས་གསུངས་པ་ལྟར་མཁས་པར་བྱ་བའི་གནས་བཅུ་ལ་བསླབ་པར་བྱ་སྟེ།
      གང་ཞེ་ན་ཕུང་པོ་ལ་མཁས་པ་དང་། དེ་བཞིན་དུ་ཁམས་དང་། སྐྱེ་མཆེད་དང་། རྟེན་འབྲེལ་དང་།
      གནས་དང་གནས་མ་ཡིན་པ་དང་། དབང་པོ་དང་། དུས་དང་། བདེན་པ་དང་། ཐེག་པ་དང་། འདུས་བྱས་འདུས་མ་བྱས་ལ་མཁས་པ་དང་བཅུའོ།
      །འདི་བཅུ་གཏན་ལ་ཕབ་པའི་ཤུགས་ཀྱིས་སྤང་བྱ་བདག་ཏུ་ལྟ་བ་བཅུ་ལྡོག་པ་སོགས་ལྟ་བ་ངན་པའི་རྨོངས་པ་ཀུན་ལས་གྲོལ་ཞིང་།
      ཇི་ལྟ་ཇི་སྙེད་ཀྱི་བློ་གྲོས་རྒྱས་པར་འགྱུར་བ་ཡིན་ནོ། །
    bo: ༄༅། །འདིར་ཤེས་བྱའི་གནས་མ་ནོར་བར་གཏན་ལ་འབེབས་པའི་ཤེས་རབ་ཐོབ་པར་འདོད་པས་མདོ་དང་བསྟན་བཅོས་ཆེན་པོ་རྣམས་ལས་གསུངས་པ་ལྟར་མཁས་པར་བྱ་བའི་གནས་བཅུ་ལ་བསླབ་པར་བྱ་སྟེ།
      གང་ཞེ་ན་ཕུང་པོ་ལ་མཁས་པ་དང་། དེ་བཞིན་དུ་ཁམས་དང་། སྐྱེ་མཆེད་དང་། རྟེན་འབྲེལ་དང་།
      གནས་དང་གནས་མ་ཡིན་པ་དང་། དབང་པོ་དང་། དུས་དང་། བདེན་པ་དང་། ཐེག་པ་དང་། འདུས་བྱས་འདུས་མ་བྱས་ལ་མཁས་པ་དང་བཅུའོ།
      །འདི་བཅུ་གཏན་ལ་ཕབ་པའི་ཤུགས་ཀྱིས་སྤང་བྱ་བདག་ཏུ་ལྟ་བ་བཅུ་ལྡོག་པ་སོགས་ལྟ་བ་ངན་པའི་རྨོངས་པ་ཀུན་ལས་གྲོལ་ཞིང་།
      ཇི་ལྟ་ཇི་སྙེད་ཀྱི་བློ་གྲོས་རྒྱས་པར་འགྱུར་བ་ཡིན་ནོ། །
